on:
    push: # Trigger the workflow on push events
        branches:
            - main # Push events to main branch
    schedule:
        - cron: '0 0 * * 0' # Trigger the workflow every Sunday at 00:00 UTC

permissions: # Define permissions for the workflow
    contents: read
    packages: write


jobs:
    github-runner-container-build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: sign in to GitHub Container Registry
              run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            - name: Build and push Docker image to ghcr.io
              uses: docker/build-push-action@v6
              with:
                    context: .
                    file: ./Dockerfile.github
                    push: true
                    tags: ghcr.io/${{ github.repository }}/github-runner:latest

        
    azure-devops-agent-container-build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: sign in to GitHub Container Registry
              run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin


            - name: Build and push Docker image to ghcr.io
              uses: docker/build-push-action@v6
              with:
                    context: .
                    file: ./Dockerfile.azure-pipelines
                    push: true
                    tags: ghcr.io/${{ github.repository }}/azure-devops-agent:latest